### ISSUE TITLE
Accept pull-request for NNE region updates?

### ISSUE THREAD

**Issue by matthew1001** [philliphoff/carwings2#12]
I've forked the repo here https://github.com/matthew1001/carwings2-mrw and updated the code to work for the NNE (Europe) region. There are a bunch of temporary changes in my fork (my own custom build scripts etc) that I plan to remove, different git URL etc., but once those are taken back out are you happy accepting the changes as a PR?

**Comment by philliphoff** [comment]
By all means, submit a PR.  I assume it's mostly just changes related to the different endpoint.  If that's the case, then it should be a quick merge.  (Note that I no longer own a Leaf, sadly, so I have to assume and trust that you've tested the changes yourself.)

**Comment by matthew1001** [comment]
It's a variety of stuff, including using the correct BASE_ENDPOINT based on region, but I've also added a request method to the Api class for each of the major REST endpoints documented at https://github.com/joshperry/carwings/blob/master/protocol.markdown and added some samples showing how each of those request functions can be used. I own a leaf that I've tested all of the new requests with, so hopefully the chances of having regressed behaviour for American Leaf's is pretty low.

**Comment by philliphoff** [comment]
Resolved with #13.
