### ISSUE TITLE
Carwings Error Handling

### ISSUE THREAD

**Issue by Tobias-Georg** [philliphoff/carwings2#21]
Hi,
With my 2018 Leaf in Belgium, Carwings2 works fine most of the time. I use Python 3.7.3.
Sometimes I get errors that I could not properly analyze as I did not output the log into a file. 
Now, I added error handling in my object that calls Carwings and stream the logging into a file. 
Last night I got the following 2 errors:

1)
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":401}'
ERROR:pycarwings2.pycarwings2:carwings   error; logging in and trying request again: {'status': 401}
-- after this, logging in and getting the parameters worked normally

2) at 2020-11-30 07:53 in the Brussels time zone:
DEBUG:pycarwings2.pycarwings2:Response HTTP Status Code: 503
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>**503 Service Temporarily Unavailable**</title>\n</head><body>\nService Temporarily Unavailable\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n'
ERROR:pycarwings2.pycarwings2:Invalid JSON returned
ERROR:root:CarWingsError
--- My program kept trying every 2 minutes and got the same error message for about 10 min.
--- After that logging in was successful, but the response flag stayed 0 for 8 attempts. Then I got:
DEBUG:pycarwings2.pycarwings2:Response HTTP Response Body: b'{"status":401}'
ERROR:pycarwings2.pycarwings2:carwings error; logging in and trying request again: {'status': 401}
--- after that, the response was normal

As a learning, I will reduce the frequency of requests when I get a 503 error.
My conclusion: the Carwings2 module works fine.

**Comment by Tobias-Georg** [comment]
As said in the edited initial post:  the problem was that I did not do proper error logging and handling in my applicaiton. Carwings2 works fine. Thanks!

**Comment by philliphoff** [comment]
@Tobias-Georg Glad you were able to find your issue and that the library still works for you.  Unfortunately, I've not owned a Leaf for nearly 4 years, so I've not been able to ensure (myself) that the library continues to match changes Nissan makes to their APIs.
